### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [Dimitriy-Gulyaev/JavaTask2#1]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**tail**
Выделение из текстового файла его конца некоторого размера:
- fileN задаёт имя входного файла. Если параметр отсутствует, следует считывать входные данные с консольного ввода. Если параметров несколько, то перед выводом для каждого файла следует вывести его имя в отдельной строке.
- Флаг -o ofile задаёт имя выходного файла (в данном случае ofile). Если параметр отсутствует, следует выводить результат на консольный вывод.
- Флаг -с num, где num это целое число, говорит о том, что из файла нужно извлечь последние num символов.
- Флаг -n num, где num это целое число, говорит о том, что из файла нужно извлечь последние num строк.

Command line: tail [-c num|-n num] [-o ofile] file0 file1 file2 …

В случае, когда какое-нибудь из имён файлов неверно или указаны одновременно флаги -c и -n, следует выдать ошибку. Если ни один из этих флагов не указан, следует вывести последние 10 строк.

Кроме самой программы, следует написать автоматические тесты к ней.

В readme также необходимо добавить инструкцию по сборке и запуску Вашего консольного приложения. Лучше всего, чтобы сборка/запуск были офрмлены в виде скриптов.

**Comment by JohnKhandygo** [comment]
По базовой реализации:
- [x] Не сохраняются переносы строк при `numberOfChars != 0`.
- [x] Неэффективное чтение из файла: Вы держите все содержимое файла в памяти программы. То есть при чтении больших файлов программа может упасть из-за недостатка выделенной ей оперативной памяти. 
- [x] Черт ногу сломит в обработке случая `numberOfChars != 0`. Почти наверняка можно проще: тольку первую строку вывода в этом случае надо выводить посимвольно (и то можно сделать `substring`), последующие строки выводятся целиком. 
- [x] В принципе разработанная функциональность работает только с файлами. То есть сейчас тесты покрывают полную связку. Если продолжите в том же духе, то и консольный ввод/вывод придется в тестах покрывать.

В остальном выглядит более менее. Можете приступать к написанию консольной оболочки.

**Comment by Mr-Shpinks** [comment]
Проверьте, пожалуйста, то, что есть.

**Comment by JohnKhandygo** [comment]
Вы не исправили одно достаточно существенное замечание про чтение всего содержимого файла/консоли в память программы, поэтому оценка за это задание 4.5, -0.5 штрафа за последнюю аттестацию. Итого второе задание зачтено на 4.
