### ISSUE TITLE
Common issues

### ISSUE THREAD

**Issue by JohnKhandygo** [Dimitriy-Gulyaev/JavaTask2#2]
- [x] (3) По условию задания допускается подача на вход нескольких файлов. Текущая реализация способна обработать только один.

**Comment by Mr-Shpinks** [comment]
Постарался сделать на 5, проверьте, пожалуйста. Очень хотелось бы третье задание получить.

**Comment by JohnKhandygo** [comment]
Третье выдал, оценку за второе поставлю по факту после проверки (то есть исправить что-то еще у Вас возможности не будет).
