### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [Dimitriy-Gulyaev/JavaTask2#5]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Русские шашки**
Реализовать игру Русские шашки для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила здесь: https://ru.wikipedia.org/wiki/Русские_шашки

**Comment by Mr-Shpinks** [comment]
Ссылка на репозиторий с третьим заданием: https://github.com/Dimitriy-Gulyaev/JavaTask3
Если вдруг успеете проверить - там только логика + тесты, на троечку.

**Comment by JohnKhandygo** [comment]
Перенес описание задания в новый репозиторий, все замечания будут появляться там.
